spring:
  elasticsearch:
    rest:
#      uris: http://192.168.0.116:9200
      uris: http://192.168.0.157:9200,http://192.168.0.158:9200,http://192.168.0.159:9200
server:
  port: 9729
winfo:
  megic:
    #极光代理IP获取地址
    jgip: http://http.tiqu.alicdns.com/getip3?num=1&type=1&pro=0&city=0&yys=0&port=1&time=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=5&mr=1&regions=110000,150000,330000,360000,410000,440000,510000,610000&gm=4
    #中国港口进程标志
    flag: 0
    #中国港口进程切割数
    flagNumb : 1
    #中国港口线程数量
    thread_numb: 2
    #国家水上交通线程数量
    ms_thread_numb: 2
    #船讯网线程数量
    shipxy_thread_numb: 2
    #船讯网爬取地址
    shipxy_address: http://www.shipxy.com/ship/getareashipssimple
    #中国港口爬取地址
    address: http://ship.chinaports.com/shipinit.do
    #南保爬取地址
    nbAddress: http://219.137.32.78:7302/ship/getShip
    #南保线程数量
    nb_thread_numb: 3
    #航保获取所有水文站
    hb_swz: https://www.nhhb.org.cn/nbwebgis/page/getAllSwz
    #航保vhf基站
    hb_vhf: https://www.nhhb.org.cn/nbwebgis/page/getAllRadio
    #航保标注
    hb_bz: https://www.nhhb.org.cn/nbwebgis/mark/listAllByType
    #航保航标
    hb_hb: https://www.nhhb.org.cn/nbwebgis/page/getNaviMarkList
    #航保AIS基站
    hb_ais: https://www.nhhb.org.cn/nbwebgis/page/getAisbsList
    #航保港口
    hb_port: https://www.nhhb.org.cn/nbwebgis/page/getAllGkLocal
    #e航保港口
    ehb_port: http://219.137.32.78:7302/page/getAllGkLocal
    #国家水上交通信息服务平台登录地址
    ms_ais: https://www.myships.com/sp/region/latest/shipinfo
    #船顺网AIS
    ships66: http://ais.ships66.com/ship/ais/getExtent2
    #客户端信息
    user_agent:
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60
      - Opera/8.0 (Windows NT 5.1; U; en)
      - Mozilla/5.0 (Windows NT 5.1; U; en; rv:1.8.1) Gecko/20061208 Firefox/2.0.0 Opera 9.50
      - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.50
      - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
      - Mozilla/5.0 (X11; U; Linux x86_64; zh-CN; rv:1.9.2.10) Gecko/20100922 Ubuntu/10.10 (maverick) Firefox/3.6.10
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36
      - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11
      - Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.133 Safari/534.16
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36
      - Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.11 TaoBrowser/2.0 Safari/536.11
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.71 Safari/537.1 LBBROWSER
      - Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; LBBROWSER)
      - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E; LBBROWSER)
      - Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; QQBrowser/7.0.3698.400)
      - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; QQDownload 732; .NET4.0C; .NET4.0E)
      - Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.84 Safari/535.11 SE 2.X MetaSr 1.0
      - Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SV1; QQDownload 732; .NET4.0C; .NET4.0E; SE 2.X MetaSr 1.0)
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.3.4000 Chrome/30.0.1599.101 Safari/537.36
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 UBrowser/4.0.3214.0 Safari/537.36

